name: CI

on:
  push:
    branches:
      - main
      - v2

permissions:
  id-token: write
  contents: write

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup turborepo cache
        uses: rharkor/caching-for-turbo@v2.2.1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build playground
        run: pnpm build:playground

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: playground/dist

      # - name: Publish packages to NPM
      #   shell: bash
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken="${{ secrets.NPM_TOKEN }}"" > ~/.npmrc
      #     pnpm -r --filter='./apps/*' publish --access public --provenance
